name: flutter_veepoo_sdk_android
description: "Veepoo SDK Smartwatch for Flutter."
version: 0.0.1
repository: https://github.com/arifai/flutter_veepoo_sdk
issue_tracker: https://github.com/arifai/flutter_veepoo_sdk/issues
topics: 
  - bluetooth 
  - ble 
  - smartwatch 
  - veepoo

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: site.shasmatic.flutter_veepoo_sdk_android
        pluginClass: FlutterVeepooSdkAndroidPlugin